using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class JoinRoom_Network 
{
    [RealtimeProperty(1, true, true)]
    private int _counter;
    
    
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class JoinRoom_Network : RealtimeModel {
    public int counter {
        get {
            return _counterProperty.value;
        }
        set {
            if (_counterProperty.value == value) return;
            _counterProperty.value = value;
            InvalidateReliableLength();
            FireCounterDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(JoinRoom_Network model, T value);
    public event PropertyChangedHandler<int> counterDidChange;
    
    public enum PropertyID : uint {
        Counter = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _counterProperty;
    
    #endregion
    
    public JoinRoom_Network() : base(null) {
        _counterProperty = new ReliableProperty<int>(1, _counter);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _counterProperty.UnsubscribeCallback();
    }
    
    private void FireCounterDidChange(int value) {
        try {
            counterDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _counterProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _counterProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Counter: {
                    changed = _counterProperty.Read(stream, context);
                    if (changed) FireCounterDidChange(counter);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _counter = counter;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
