using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class Start_Networking 
{
    [RealtimeProperty(1, true, true)]
    private int _touchcount;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class Start_Networking : RealtimeModel {
    public int touchcount {
        get {
            return _touchcountProperty.value;
        }
        set {
            if (_touchcountProperty.value == value) return;
            _touchcountProperty.value = value;
            InvalidateReliableLength();
            FireTouchcountDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(Start_Networking model, T value);
    public event PropertyChangedHandler<int> touchcountDidChange;
    
    public enum PropertyID : uint {
        Touchcount = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _touchcountProperty;
    
    #endregion
    
    public Start_Networking() : base(null) {
        _touchcountProperty = new ReliableProperty<int>(1, _touchcount);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _touchcountProperty.UnsubscribeCallback();
    }
    
    private void FireTouchcountDidChange(int value) {
        try {
            touchcountDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _touchcountProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _touchcountProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Touchcount: {
                    changed = _touchcountProperty.Read(stream, context);
                    if (changed) FireTouchcountDidChange(touchcount);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _touchcount = touchcount;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
